= HowTo
Dieter Baier <git@dieterbaier.eu>
:toc:

== Remember password of private key for different SSH-Sessions
If you use different SSH-Keys on different destinations you might not have to enter the password for each ssh-command every time.
For that reason you can use the ssh-agent, who stores your passwords at least within one session.

You should have two things done:

* Have a alias for your host configured within the ssh-config: 

.~/.ssh/config
----
Host bitbucket.org
  HostName bitbucket.org
  User yourUserName
  AddKeysToAgent yes
  IdentityFile "~/path/to/your/bitbucket/id_rsa.file"

Host github.com
  HostName github.com
  User git
  AddKeysToAgent yes
  IdentityFile "~/path/to/your/github/id_rsa.file"
----
With this configuration, you would be asked for the password (in case you have one password at your file), as soon you try to ssh-connect either to bitbucket.org or to github.com.

If you like, not to enter your password all the time during the session, you should have the second point done as well:

* Have a bash-scricpt, which opens the ssh-agent automatically when you open a shell

.~/.bashrc
----
env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
    (umask 077; ssh-agent >| "$env")
    . "$env" >| /dev/null ; }

agent_load_env

# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
    agent_start
    ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
    ssh-add
fi

unset env
----

